<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\GoogleReviewsSR\Block\Widget\Slider;
 use Magento\Framework\Escaper;

/** @var Slider $block */
/** @var Escaper $escaper */

$accountInfo = $block->getAccountInfo();
$sliderConfig = $block->getSlickConfig();
$defaultBreakpoints = (object) [
    '480' => '1',
    '768' => '2',
    '1024' => '3'
];
$uniqId = rand();

$txtLen = 3;
if ($block->getTextLengthClass() == 'medium') $txtLen = 5;
if ($block->getTextLengthClass() == 'large')  $txtLen = 7;
?>

<?php if (!empty($accountInfo)): ?>
<section class="googlereviews-widget-slider" x-data="initReviewSlider_<?= $uniqId ?>">
    <?php if ($block->getTitle()): ?>
        <h3 class="text-xl font-semibold tracking-wider text-stone-700 mb-4 text-center">
            <?= $escaper->escapeHtml($block->getTitle()) ?>
        </h3>
    <?php endif; ?>

    <div class="widget-list relative"
         :class="{ 'px-10': options.arrows && slideOnPage > 1 }"
         :resize.window="resizeSlider"
         @resize.window="resizeSlider"
         @mouseover="options.autoplay ? clearInterval(interval) : null"
         @mouseout="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null"
         @touchstart="options.autoplay ? clearInterval(interval) : null"
         @touchend="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null">

        <div class="additional-wrapper overflow-hidden select-none"
             @mouseup="mouseEvent($event)"
             @mousedown="mouseEvent($event)"
             @touchend="mouseEvent($event)"
             @touchstart="mouseEvent($event)">

            <div class="flex transition-transform"
                :style="`transform: translateX(${currentTransform}); transition-duration: ${transformDuration};`"
                :resize.window="setSLideStep($el)"
                @resize.window="setSLideStep($el)">
                <?php foreach ($reviews = $block->getReviews() as $review): ?>
                    <div class="slide-wrapper flex px-2" :style="{ 'min-width': slideWidth }">
                        <div class="widget-item flex flex-col w-full border p-4 rounded-lg border-stone-200 bg-white">
                            <div class="flex items-center gap-5 justify-between mb-3">
                                <span class="opacity-50 text-sm italic">
                                    <?= $escaper->escapeHtml($review['created']) ?>
                                </span>
                                <span class="rating-summary relative inline-block -mr-1">
                                    <span class="empty-starts flex text-stone-200">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                        </svg>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                        </svg>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                        </svg>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                        </svg>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                        </svg>
                                    </span>

                                    <span class="filling-starts absolute top-0 text-[#3879bd] overflow-hidden"
                                            style="width: <?= $escaper->escapeHtml(__('%1%', $review['total']*20)); ?>">

                                        <span class="inline-flex">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                            </svg>
                                        </span>
                                    </span>
                                </span>
                            </div>
                            <div class="review-info text-stone-700 overflow-hidden"
                                 style="display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: <?=$escaper->escapeHtml($txtLen)?>;">
                                <?= $escaper->escapeHtml($review['comment']) ?>
                            </div>
                            <div class="opacity-50 text-sm italic mt-auto pt-4">
                                <?= $escaper->escapeHtml($review['name']) ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <template x-if="options.arrows && slideOnPage > 1" >
            <div class="slider-arrow">
                <span class="arrow-left absolute left-0 bottom-1/2 translate-y-3 p-1 border border-stone-300 bg-white rounded-full
                            cursor-pointer transition-color duration-300 hover:bg-stone-100"
                      @click="arrowPrev">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
                    </svg>
                </span>
                <span class="arrow-right absolute right-0 bottom-1/2 translate-y-3 p-1 border border-stone-300 bg-white rounded-full
                            cursor-pointer transition-color duration-300 hover:bg-stone-100"
                      @click="arrowNext">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                    </svg>
                </span>
            </div>
        </template>

        <template x-if="options.dots && slideOnPage > 1" >
            <div class="slider-thumb flex flex-wrap gap-2 justify-center mt-2">
                <template x-for="(dot, index) in new Array(slideOnPage)">
                    <span class="inline-block w-3 h-3 rounded-full border border-stone-300 cursor-pointer
                                transition-colors duration-300"
                          :class="{ 'border-[#3879bd] bg-[#3879bd]': activeSlidePage == index + 1 }"
                          @click="setSlidePage(index + 1)"></span>
                </template>
            </div>
        </template>
    </div>

    <?php if ($block->showSummary()): ?>
        <footer class="widget-footer mt-4 text-center">
            <?php foreach ($accountInfo as $account): ?>
                <aside class="text-sm text-stone-700">
                    <?= $escaper->escapeHtml(__('Reviewed with a score of ')) ?>
                    <b><?= $escaper->escapeHtml($account['avgRatingScore']) ?></b>
                    <?= $escaper->escapeHtml(__(' based on ')) ?>
                    <a  class="text-[#3879bd] text-sm transition-opacity duration-300 hover:opacity-80 underline underline-offset-2"
                        href="<?= $escaper->escapeUrl($block->getUrl('googlereviews')); ?>">
                        <?= $escaper->escapeHtml(__('%1 reviews', $account['total'])) ?>
                    </a>
                </aside>
            <?php endforeach; ?>
        </footer>
    <?php endif; ?>
</section>
    
<script>
    'use strict';

    function initReviewSlider_<?= $uniqId ?>() {
        return {
            options: {
                dots: <?= isset($sliderConfig['dots']) ? $sliderConfig['dots'] : 0 ?>,
                arrows: <?= isset($sliderConfig['arrows']) ? $sliderConfig['arrows'] : 0 ?>,
                autoplay: <?= isset($sliderConfig['autoplay']) ? $sliderConfig['autoplay'] : 0 ?>,
                autoplaySpeed: <?= isset($sliderConfig['autoplaySpeed']) ? $sliderConfig['autoplaySpeed'] : 3000 ?>,
                slidesToShow: <?= isset($sliderConfig['slidesToShow']) ? $sliderConfig['slidesToShow'] : 4 ?>,
                breakpoints: <?= isset($sliderConfig['responsiveJson']) 
                                    ? json_encode($sliderConfig['responsiveJson']) 
                                    : json_encode($defaultBreakpoints) ?>,
            },

            slideWidth: '100%',
            slideCount: <?= count($block->getReviews()); ?>,
            slideOnPage: 1,
            activeSlidePage: 1,

            wrapperWidth: 0,
            stepWidth: 0,
            currentTransform: '0',
            transformDuration: '1.5s',

            interval: null,
            axisShiftX: 0, 

            init() {
                if (this.options.autoplay) {
                    this.interval = setInterval(() => { this.arrowNext() }, this.options.autoplaySpeed);
                }
            },

            resizeSlider() {
                // default state
                this.slideWidth = `${100 / this.options.slidesToShow}%`;
                this.slideOnPage = Math.ceil(this.slideCount / this.options.slidesToShow);

                const pObj = this.options.breakpoints,
                      pArr = Object.keys(pObj).sort((a,b) => b - a),
                      pLen = pArr.length;

                for (let i = 0; i < pLen; i++) {
                    if (window.innerWidth < +pArr[i]) { 
                        this.slideWidth = `${100 / +pObj[pArr[i]]}%`;
                        this.slideOnPage = Math.ceil(this.slideCount / +pObj[pArr[i]]);
                    }
                }

                // check active slide after resizing
                if (this.activeSlidePage > this.slideOnPage) this.activeSlidePage = this.slideOnPage;
            },

            setSlidePage(num) {
                this.activeSlidePage = num;

                if (!num) this.currentTransform = '0';

                if ((this.wrapperWidth - this.stepWidth) >= this.stepWidth * (num - 1) && num) {
                    this.currentTransform = `-${this.stepWidth * (num - 1)}px`;
                } else {
                    this.currentTransform = `-${this.wrapperWidth - this.stepWidth}px`;
                }

                setTimeout(() => { this.transformDuration = '1.5s' }, 50);
            },

            setSLideStep(el) {
                setTimeout(() => {
                    this.wrapperWidth = el.scrollWidth; 
                    this.stepWidth = el.clientWidth;
                    this.transformDuration = '0s';
                    this.setSlidePage(this.activeSlidePage);
                }, 50);
            },

            arrowNext() {
                this.activeSlidePage + 1 <= this.slideOnPage
                    ? this.setSlidePage(this.activeSlidePage + 1)
                    : this.setSlidePage(1);
            },

            arrowPrev() {
                this.activeSlidePage - 1 >= 1
                    ? this.setSlidePage(this.activeSlidePage - 1)
                    : this.setSlidePage(this.slideOnPage);
            },

            mouseEvent(event) {
                if (event.type == 'mousedown' || event.type == 'touchstart') {
                    this.axisShiftX = event.pageX || event.changedTouches[0].pageX;
                } 

                if (event.type == 'mouseup' || event.type == 'touchend') {
                    let endTouch = event.pageX || event.changedTouches[0].pageX;

                    if (endTouch < this.axisShiftX) this.arrowNext();
                    if (endTouch > this.axisShiftX) this.arrowPrev();
                }
            }
        }
    }
</script>
<?php endif; ?>