<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\GoogleReviewsSR\Block\Widget\Review\Carousel;
 use Magento\Framework\Escaper;
 use Hyva\Theme\ViewModel\HeroiconsOutline;
 use Hyva\Theme\Model\ViewModelRegistry;

/** @var Carousel $block */
/** @var Escaper $escaper */
/** @var HeroiconsOutline $heroicons */

$uniqId = rand();
$reviewsMaxRating = $block->getReviewsMaxRating();

if ($block->getTextLength() == 'small')  $txtLen = 2;
if ($block->getTextLength() == 'medium') $txtLen = 4;
if ($block->getTextLength() == 'large')  $txtLen = 6;

$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<section data-element="google-carousel-widget-<?= $uniqId; ?>" 
         x-data="GoogleCarousel_<?= $uniqId ?>">
    
    <div class="relative"
         :class="{ 'px-10': options.arrows }"
         :resize.window="resizeSlider"
         @resize.window="resizeSlider"
         @mouseover="options.autoplay ? clearInterval(interval) : null"
         @mouseout="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null"
         @touchstart="options.autoplay ? clearInterval(interval) : null"
         @touchend="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null">

         <div class="overflow-hidden select-none"
             @mouseup="mouseEvent($event)"
             @mousedown="mouseEvent($event)"
             @touchend="mouseEvent($event)"
             @touchstart="mouseEvent($event)">
             
             <div class="flex transition-transform"
                :style="`transform: translateX(${currentTransform}); transition-duration: ${transformDuration};`"
                :resize.window="setSLideStep($el)"
                @resize.window="setSLideStep($el)">

                <?php foreach ($reviews = $block->getReviews() as $review): ?>
                    <div class="px-3" :style="{ 'min-width': slideWidth }">
                        <div data-element="review-item"
                            class="flex flex-col p-4 bg-white border border-gray-200 rounded-xl shadow h-full">
                            
                            <header class="flex items-center justify-between gap-5 pb-3 mb-5 border-b border-gray-200">
                                <b class="name"><?= $escaper->escapeHtml($review['name']) ?></b>

                                <?php if ($block->showStars()): ?>
                                    <?php 
                                        $starColor = $block->getSelectColor() ? $block->getSelectColor() : '#000000';
                                    ?>

                                    <?= $block->getLayout()
                                        ->createBlock('Magento\Framework\View\Element\Template')
                                        ->setTemplate('Magmodules_GoogleReviewsSR::widget/helper/stars.phtml')
                                        ->setData('svgSize', '18')
                                        ->setData('starColor', $starColor)
                                        ->setData('percent', floatval($review['total']) / $reviewsMaxRating * 100)
                                        ->toHtml();
                                    ?>
                                <?php endif;?>
                            </header>

                            <?php if (trim($review['comment'])): ?>
                                <div class="comment mb-5 text-sm leading-6 opacity-70 overflow-hidden"
                                    style="display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: <?=$escaper->escapeHtml($txtLen)?>;">
                                    <?= $escaper->escapeHtml($review['comment']) ?>
                                </div>
                            <?php endif;?>

                            <footer class="mt-auto grid-cols-[28px_1fr] items-center gap-3 pt-4 border-t border-gray-200
                                        <?= !$block->showIcon() ? 'block' : 'grid' ?>">

                                <?php if ($block->showIcon()): ?>
                                    <img src="<?= $escaper->escapeUrl($block->getSmallLogoUrl()); ?>" width="26" height="26"
                                         alt="<?= $escaper->escapeHtmlAttr(__('Google carousel widget')); ?>" />
                                <?php endif;?>

                                <span class="opacity-70 text-sm">
                                    <?= $escaper->escapeHtml(__('A Google Review written %1', $review['created'])); ?>
                                </span>
                            </footer>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>

        <template x-if="options.arrows" >
            <div class="slider-arrow">
                <span class="absolute left-0 bottom-1/2 translate-y-3 p-1 opacity-50
                             cursor-pointer transition-opacity duration-300 hover:opacity-75"
                    data-element="arrow-left"
                    @click="arrowPrev">
                    <?= $heroicons->chevronLeftHtml('', 16, 16); ?>
                </span>

                <span class="arrow-right absolute right-0 bottom-1/2 translate-y-3 p-1 opacity-50
                             cursor-pointer transition-opacity duration-300 hover:opacity-75"
                    data-element="arrow-right"
                    @click="arrowNext">
                    <?= $heroicons->chevronRightHtml('', 16, 16); ?>
                </span>
            </div>
        </template>
    </div>
</section>

<script>
    'use strict';

    function GoogleCarousel_<?= $uniqId ?>() {
        return {
            options: {
                arrows: <?= json_encode($block->showNavigationArrows()); ?>,
                autoplay: <?= json_encode($block->isAutoplay()); ?>,
                autoplaySpeed: 3000,
                slidesToShow: 4,
                breakpoints: {
                    '639': 1,
                    '1023': 2,
                    '1279': 3,
                    '2500': 4,
                },
            },

            slideWidth: '100%',
            slideCount: <?= count($block->getReviews()); ?>,
            slideOnPage: 1,
            activeSlidePage: 1,

            wrapperWidth: 0,
            stepWidth: 0,
            currentTransform: '0',
            transformDuration: '1.5s',

            interval: null,
            axisShiftX: 0, 

            init() {
                if (this.options.autoplay) {
                    this.interval = setInterval(() => { this.arrowNext() }, this.options.autoplaySpeed);
                }
            },

            setSlidePage(num) {
                this.activeSlidePage = num;

                if (!num) this.currentTransform = '0';

                if ((this.wrapperWidth - this.stepWidth) >= this.stepWidth * (num - 1) && num) {
                    this.currentTransform = `-${this.stepWidth * (num - 1)}px`;
                } else {
                    this.currentTransform = `-${this.wrapperWidth - this.stepWidth}px`;
                }

                setTimeout(() => { this.transformDuration = '1.5s' }, 50);
            },

            resizeSlider() {
                // default state
                this.slideWidth = `${100 / this.options.slidesToShow}%`;
                this.slideOnPage = this.slideCount - this.options.slidesToShow;

                const pObj = this.options.breakpoints,
                    pArr = Object.keys(pObj).sort((a,b) => b - a),
                    pLen = pArr.length;

                for (let i = 0; i < pLen; i++) {
                    if (window.innerWidth < +pArr[i]) { 
                        this.slideWidth = `${100 / +pObj[pArr[i]]}%`;
                        this.options.slidesToShow = +pObj[pArr[i]];
                        this.slideOnPage = this.slideCount - +pObj[pArr[i]];
                    }
                }

                // check active slide after resizing
                if (this.activeSlidePage > this.slideOnPage) this.activeSlidePage = this.slideOnPage;
            },

            setSLideStep(el) {
                setTimeout(() => {
                    this.wrapperWidth = el.scrollWidth; 
                    this.stepWidth = Math.ceil(el.clientWidth / this.options.slidesToShow);
                    this.transformDuration = '0s';
                    this.setSlidePage(this.activeSlidePage);
                }, 50);
            },

            arrowNext() {
                this.activeSlidePage + 1 <= this.slideOnPage
                    ? this.setSlidePage(this.activeSlidePage + 1)
                    : this.setSlidePage(1);
            },

            arrowPrev() {
                this.activeSlidePage - 1 >= 1
                    ? this.setSlidePage(this.activeSlidePage - 1)
                    : this.setSlidePage(this.slideOnPage);
            },

            mouseEvent(event) {
                if (event.type == 'mousedown' || event.type == 'touchstart') {
                    this.axisShiftX = event.pageX || event.changedTouches[0].pageX;
                } 

                if (event.type == 'mouseup' || event.type == 'touchend') {
                    let endTouch = event.pageX || event.changedTouches[0].pageX;

                    if (endTouch < this.axisShiftX) this.arrowNext();
                    if (endTouch > this.axisShiftX) this.arrowPrev();
                }
            }
        }
    }
</script>
