<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\GoogleReviewsSR\Block\Widget\Review\Sidebar;
 use Magento\Framework\Escaper;
 use Hyva\Theme\ViewModel\HeroiconsOutline;
 use Hyva\Theme\Model\ViewModelRegistry;

/** @var Sidebar $block */
/** @var Escaper $escaper */
/** @var HeroiconsOutline $heroicons */

$uniqId = $block->getUniqueId();

$reviewsCount = $block->getReviewsCount();
$reviewsCurrentRating = $block->getReviewsCurrentRating();
$reviewsMaxRating = $block->getReviewsMaxRating();

if ($block->getTextLength() == 'small')  $txtLen = 2;
if ($block->getTextLength() == 'medium') $txtLen = 4;
if ($block->getTextLength() == 'large')  $txtLen = 6;

$heroicons = $viewModels->require(HeroiconsOutline::class);
$reviewLabel = $reviewsCount > 1 ? __('reviews') : __('review');
?>

<section data-element="google-sidebar-widget-<?= $uniqId; ?>"
         x-data="GoogleSidebar_<?= $uniqId ?>"
         class="max-w-xs bg-white border border-gray-200 rounded-xl shadow overflow-hidden">
    
    <header class="grid gap-1.5 p-4 bg-[#f9f9f9]">
        <?php if ($block->showLogoInHeader() || $block->showStarsInHeader()): ?>
            <div data-element="box-summary"
                 class="flex items-center justify-between gap-11">

                <?php if ($block->showLogoInHeader()): ?>
                    <img src="<?= $escaper->escapeUrl($block->getBigLogoUrl()); ?>" width="83" height="28"
                         alt="<?= $escaper->escapeHtmlAttr(__('Google sidebar widget')); ?>" />
                <?php endif; ?>

                <?php if ($block->showStarsInHeader()): ?>
                    <?= $block->getLayout()
                            ->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Magmodules_GoogleReviewsSR::widget/helper/stars.phtml')
                            ->setData('svgSize', '22')
                            ->setData('percent', $reviewsCurrentRating / $reviewsMaxRating * 100)
                            ->toHtml();
                    ?>
                <?php endif;?>
            </div>
        <?php endif;?>

        <div data-element="box-information"
             class="flex gap-5 justify-between">
            <div>
                <?= $escaper->escapeHtml(__('<b>%1</b> based on <b>%2 %3</b>', $reviewsCurrentRating, $reviewsCount, $reviewLabel), ['b']); ?>
            </div>
        </div>
    </header>

    <div class="relative pb-4"
         @mouseover="options.autoplay ? clearInterval(interval) : null"
         @mouseout="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null"
         @touchstart="options.autoplay ? clearInterval(interval) : null"
         @touchend="options.autoplay ? interval = setInterval(() => { arrowNext() }, options.autoplaySpeed) : null">

        <div class="overflow-hidden select-none"
             @mouseup="mouseEvent($event)"
             @mousedown="mouseEvent($event)"
             @touchend="mouseEvent($event)"
             @touchstart="mouseEvent($event)">

            <div class="flex transition-transform"
                 data-element="google-sidebar-slider"
                 :style="`transform: translateX(${currentTransform}); transition-duration: ${transformDuration};`"
                 :resize.window="setSLideStep($el)"
                 @resize.window="setSLideStep($el)">

                <?php foreach ($reviews = $block->getReviews() as $review): ?>
                    <div class="px-2 min-w-full">
                        <div data-element="review-item" class="flex flex-col px-4 pt-4">
                            <header class="flex justify-between gap-5 pb-3 mb-5 border-b border-gray-200">
                                <b class="name"><?= $escaper->escapeHtml($review['name']) ?></b>

                                <?php if ($block->showStarsPerReview()): ?>
                                    <?php
                                        $starColor = $block->getSelectColor() ? $block->getSelectColor() : '#000000';
                                    ?>

                                    <?= $block->getLayout()
                                        ->createBlock('Magento\Framework\View\Element\Template')
                                        ->setTemplate('Magmodules_GoogleReviewsSR::widget/helper/stars.phtml')
                                        ->setData('svgSize', '18')
                                        ->setData('starColor', $starColor)
                                        ->setData('percent', $reviewsCurrentRating / $reviewsMaxRating * 100)
                                        ->toHtml();
                                    ?>
                                <?php endif; ?>
                            </header>

                            <?php if (trim($review['comment'])): ?>
                                <div class="comment opacity-70 text-sm leading-6"
                                    style="display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: <?=$escaper->escapeHtml($txtLen)?>;">
                                    <?= $escaper->escapeHtml($review['comment']) ?>
                                </div>
                            <?php endif;?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>

        <!-- Dots -->
        <div class="flex flex-wrap gap-2 justify-center mt-7 px-9">
            <template x-for="(dot, index) in new Array(slideOnPage)">
                <span class="inline-block w-3 h-3 rounded-full border bg-gray-300 cursor-pointer
                            transition-colors duration-300"
                        :class="{ '!bg-black': activeSlidePage == index + 1 }"
                        @click="setSlidePage(index + 1)"></span>
            </template>
        </div>

        <!-- Arrow -->
        <template x-if="options.arrows" >
            <div class="slider-arrow absolute bottom-5 left-1 right-1">
                <span class="absolute left-0 bottom-1/2 translate-y-3 p-1 opacity-50
                             cursor-pointer transition-opacity duration-300 hover:opacity-75"
                      data-element="arrow-left"
                      @click="arrowPrev">
                    <?= $heroicons->chevronLeftHtml('', 16, 16); ?>
                </span>

                <span class="absolute right-0 bottom-1/2 translate-y-3 p-1 opacity-50
                             cursor-pointer transition-opacity duration-300 hover:opacity-75"
                      data-element="arrow-right"
                      @click="arrowNext">
                    <?= $heroicons->chevronRightHtml('', 16, 16); ?>
                </span>
            </div>
        </template>
    </div>
</section>

<script>
    'use strict';

    function GoogleSidebar_<?= $uniqId ?>() {
        return {
            options: {
                arrows: <?= json_encode($block->showNavigationArrows()); ?>,
                autoplay: <?= json_encode($block->isAutoplay()); ?>,
                autoplaySpeed: 3000,
            },

            slideOnPage: <?= count($block->getReviews()); ?>,
            activeSlidePage: 1,

            wrapperWidth: 0,
            stepWidth: 0,
            currentTransform: '0',
            transformDuration: '1.5s',

            interval: null,
            axisShiftX: 0, 

            init() {
                if (this.options.autoplay) {
                    this.interval = setInterval(() => { this.arrowNext() }, this.options.autoplaySpeed);
                }
            },

            setSlidePage(num) {
                this.activeSlidePage = num;

                if (!num) this.currentTransform = '0';

                if ((this.wrapperWidth - this.stepWidth) >= this.stepWidth * (num - 1) && num) {
                    this.currentTransform = `-${this.stepWidth * (num - 1)}px`;
                } else {
                    this.currentTransform = `-${this.wrapperWidth - this.stepWidth}px`;
                }

                setTimeout(() => { this.transformDuration = '1.5s' }, 50);
            },

            setSLideStep(el) {
                setTimeout(() => {
                    this.wrapperWidth = el.scrollWidth; 
                    this.stepWidth = el.clientWidth;
                    this.transformDuration = '0s';
                    this.setSlidePage(this.activeSlidePage);
                }, 50);
            },

            arrowNext() {
                this.activeSlidePage + 1 <= this.slideOnPage
                    ? this.setSlidePage(this.activeSlidePage + 1)
                    : this.setSlidePage(1);
            },

            arrowPrev() {
                this.activeSlidePage - 1 >= 1
                    ? this.setSlidePage(this.activeSlidePage - 1)
                    : this.setSlidePage(this.slideOnPage);
            },

            mouseEvent(event) {
                if (event.type == 'mousedown' || event.type == 'touchstart') {
                    this.axisShiftX = event.pageX || event.changedTouches[0].pageX;
                } 

                if (event.type == 'mouseup' || event.type == 'touchend') {
                    let endTouch = event.pageX || event.changedTouches[0].pageX;

                    if (endTouch < this.axisShiftX) this.arrowNext();
                    if (endTouch > this.axisShiftX) this.arrowPrev();
                }
            }
        }
    }
</script>
