<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\GoogleReviewsSR\Block\Widget\Review\Textual;
 use Magento\Framework\Escaper;

/** @var Textual $block */
/** @var Escaper $escaper */

$uniqId = $block->getUniqueId();

$reviewsCount = $block->getReviewsCount();
$reviewsCurrentRating = $block->getReviewsCurrentRating();
$reviewsMaxRating = $block->getReviewsMaxRating();

$reviewLabel = $reviewsCount > 1 ? __('reviews') : __('review');
?>

<section data-element="google-textual-widget-<?= $uniqId; ?>"
         class="inline-flex items-center flex-wrap gap-3">
    <?php if ($block->showIcons()): ?>
        <img src="<?= $escaper->escapeUrl($block->getSmallLogoUrl()); ?>" width="24" height="24"
            alt="<?= $escaper->escapeHtmlAttr(__('Google textual widget')); ?>" />
    <?php endif;?>

    <?php if ($block->showStars()): ?>
        <?= $block->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Magmodules_GoogleReviewsSR::widget/helper/stars.phtml')
                ->setData('svgSize', '20')
                ->setData('percent', $reviewsCurrentRating / $reviewsMaxRating * 100)
                ->toHtml();
        ?>
    <?php endif;?>

    <div class="text pt-0.5">
        <?= $escaper->escapeHtml(__('Our store is rated with a <b>%1</b> based on <b>%2 %3</b>', $reviewsCurrentRating, $reviewsCount, $reviewLabel), ['b']); ?>
    </div>
</section>
